apiVersion: apps/v1
kind: Deployment
metadata:
  name: mypostgres-deploy
  labels:
    app: my-postgres
    type: db

spec:
  template:
    metadata:
      name: mypostgres-pod
      labels:
        app: my-postgres
        type: db
    spec:
      containers:
      - name: mypostgres-container
        image: postgres:alpine
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: postgresvolume
            subPath: postgres
        env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mypostgres-secret
                key: PGPASSWORD
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                name: mypostgres-configmap
                key: PGDATABASE
          - name: POSTGRES_USER
            valueFrom:
              configMapKeyRef:
                name: mypostgres-configmap
                key: PGUSER
      volumes:
        - name: postgresvolume
          persistentVolumeClaim:
            claimName: mypostgres-pvc
  replicas: 1 # For DB keep replicas value as 1
  selector:
    matchLabels:
      app: my-postgres
      type: db
