apiVersion: apps/v1
kind: Deployment
metadata:
  name: myfrontend-deploy
  labels:
    component: frontend
    app: my-frontend

spec:
  template:
    metadata:
      name: myfrontend-pod
      labels:
        component: frontend
        app: my-frontend
    spec:
      containers:
        - name: myfrontend
          image: sgrams/myfrontend
          ports:
            - containerPort: 3000

  replicas: 3
  selector:
    matchLabels:
      component: frontend
      app: my-frontend
