apiVersion: v1
kind: Service
metadata:
  name: myfrontend-nodeport

spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 31110
  selector:
    component: frontend
    app: my-frontend
